FROM opensuse/leap:15
RUN zypper install -y patterns-devel-base-devel_basis patterns-devel-base-devel_kernel
RUN zypper install -y make bc libopenssl-devel libelf-devel-32bit libelf-devel indent git
RUN zypper install -y python311-base
RUN zypper install -y hostname
RUN zypper install -y gzip
